export const NEW_TRANSACTION_REQUEST = 'NEW_TRANSACTION_REQUEST'
export const NEW_TRANSACTION_SUCCESS = 'NEW_TRANSACTION_SUCCESS'
export const NEW_TRANSACTION_FAIL = 'NEW_TRANSACTION_FAIL'
export const NEW_TRANSACTION_RESET = 'NEW_TRANSACTION_RESET'

export const TRANSACTION_DETAILS_REQUEST = 'TRANSACTION_DETAILS_REQUEST'
export const TRANSACTION_DETAILS_SUCCESS = 'TRANSACTION_DETAILS_SUCCESS'
export const TRANSACTION_DETAILS_FAIL = 'TRANSACTION_DETAILS_FAIL'

export const TRANSACTION_LIST_MY_REQUEST = 'TRANSACTION_LIST_MY_REQUEST'
export const TRANSACTION_LIST_MY_SUCCESS = 'TRANSACTION_LIST_MY_SUCCESS'
export const TRANSACTION_LIST_MY_FAIL = 'TRANSACTION_LIST_MY_FAIL'
export const TRANSACTION_LIST_MY_RESET = 'TRANSACTION_LIST_MY_RESET'

export const TRANSACTION_LIST_REQUEST = 'TRANSACTION_LIST_REQUEST'
export const TRANSACTION_LIST_SUCCESS = 'TRANSACTION_LIST_SUCCESS'
export const TRANSACTION_LIST_FAIL = 'TRANSACTION_LIST_FAIL'

